/* ============================================================
   Traduceri — Șantier Manager
   ============================================================
   Fiecare limbă e un obiect: cheia e textul românesc din
   aplicație, valoarea e traducerea. Dacă adaugi o limbă nouă,
   copiezi un bloc întreg (ex. "fr: {...}"), îi schimbi codul
   (ex. "es") și traduci valorile din dreapta.

   Cheile trebuie să fie EXACT textul românesc din aplicație —
   dacă textul din app.jsx se schimbă, cheia de-aici nu se mai
   potrivește și rămâne netradusă (dar nu se strică nimic, doar
   arată în română).
   ============================================================ */

window.TRAD = {
  fr: {
    /* intrare */
    "Alege limba": "Choisis la langue",
    "Poți schimba oricând, din colțul de sus.": "Tu peux changer à tout moment, en haut à droite.",
    "🔑 Intru ca Admin": "🔑 Entrer comme Admin",
    "👷 Intru ca Muncitor": "👷 Entrer comme Ouvrier",
    "🧪 Vezi un exemplu (demo)": "🧪 Voir un exemple (démo)",
    "sau": "ou",
    "PIN admin": "Code admin",
    "Intră": "Entrer",
    "← Înapoi": "← Retour",
    "PIN greșit.": "Code incorrect.",
    "Cine ești?": "Qui es-tu ?",
    "— alege numele tău —": "— choisis ton nom —",
    "Parola ta": "Ton mot de passe",
    "Alege-ți o parolă (minim 4 cifre)": "Choisis un mot de passe (4 chiffres min.)",
    "E prima ta intrare — parola pe care o scrii acum rămâne a ta.":
      "C'est ta première connexion — le mot de passe que tu écris maintenant sera le tien.",
    "Parolă greșită. Dacă ai uitat-o, cere-i șefului să ți-o reseteze.":
      "Mot de passe incorrect. Si tu l'as oublié, demande au chef de le réinitialiser.",
    "Parola trebuie să aibă minim 4 caractere.": "Le mot de passe doit faire au moins 4 caractères.",
    "Adminul trebuie mai întâi să te adauge la Oameni → Angajați.":
      "L'admin doit d'abord t'ajouter dans Personnel → Employés.",
    /* demo */
    "Ce e modul demo": "C'est quoi le mode démo",
    "MOD DEMO": "MODE DÉMO",
    "Date de exemplu. Nimic nu se salvează și nu-ți atinge datele reale.":
      "Données d'exemple. Rien n'est enregistré, tes vraies données ne sont pas touchées.",
    "🔑 Intră ca Admin": "🔑 Entrer comme Admin",
    "Ieși": "Quitter",
    "DEMO · Ieși": "DÉMO · Quitter",
    "Admin · Ieși": "Admin · Quitter",
    /* muncitor */
    "Cont șters": "Compte supprimé",
    "Fără echipă": "Sans équipe",
    "Sculele echipei tale": "Les outils de ton équipe",
    "La voi": "Chez vous",
    "Cod": "Réf.",
    "din": "depuis",
    "Planingul tău": "Ton planning",
    "Azi": "Aujourd'hui",
    "Șantier șters": "Chantier supprimé",
    "Orele tale": "Tes heures",
    "Total:": "Total :",
    "Probleme și necesar": "Problèmes et besoins",
    "+ Raportează o problemă / cere ceva": "+ Signaler un problème / demander",
    "N-ai trimis nimic încă. Lipsește material, s-a stricat o sculă, ai nevoie de ceva pe șantier — scrie aici și vede doar șeful.":
      "Tu n'as encore rien envoyé. Il manque du matériel, un outil est cassé, tu as besoin de quelque chose — écris ici, seul le chef le voit.",
    "⚠ Problemă": "⚠ Problème",
    "📦 Necesar": "📦 Besoin",
    "Trimisă": "Envoyé",
    "Rezolvată": "Résolu",
    "Raportează": "Signaler",
    "📦 Am nevoie de…": "📦 J'ai besoin de…",
    "Ce s-a întâmplat?": "Qu'est-ce qui s'est passé ?",
    "Ce vă lipsește pe șantier?": "Qu'est-ce qui vous manque sur le chantier ?",
    "Mesajul ajunge doar la admin.": "Le message arrive uniquement à l'admin.",
    "Trimite": "Envoyer",
    /* sarcini */
    "De rezolvat": "À régler",
    "De făcut": "À faire",
    "Rezolvat": "Résolu",
    "Marchează rezolvat": "Marquer comme réglé",
    "Redeschide": "Rouvrir",
    "Rezolvat de": "Réglé par",
    "Poza nu mai e disponibilă": "La photo n'est plus disponible",
    "Se încarcă poza…": "Chargement de la photo…",
    /* navigare */
    "Panou": "Accueil",
    "Șantiere": "Chantiers",
    "Planing": "Planning",
    "Stoc": "Stock",
    "Cereri": "Demandes",
    "Setări": "Réglages",
    /* comune */
    "Salvează": "Enregistrer",
    "Modifică": "Modifier",
    "Șterge": "Supprimer",
    "Adaugă": "Ajouter",
    "Anulează": "Annuler",
    "Se încarcă…": "Chargement…",
    "Se salvează…": "Enregistrement…",
    "om": "personne",
    "oameni": "personnes",
    "zi": "jour",
    "zile": "jours",
    "ore": "heures",
    "Luni": "Lundi", "Marți": "Mardi", "Miercuri": "Mercredi", "Joi": "Jeudi",
    "Vineri": "Vendredi", "Sâmbătă": "Samedi", "Duminică": "Dimanche",
    /* --- adăugate: roluri, concedii, utilaje, planing, categorii, taxe --- */
    "Roluri și permisiuni": "Rôles et permissions",
    "cine ce poate face în aplicație": "qui peut faire quoi dans l'appli",
    "🔑 Rolurile firmei": "🔑 Les rôles de l'entreprise",
    "+ Rol nou": "+ Nouveau rôle",
    "Rol nou": "Nouveau rôle",
    "Modifică rol": "Modifier le rôle",
    "Numele rolului *": "Nom du rôle *",
    "Salvează rolul": "Enregistrer le rôle",
    "permisiune": "permission",
    "permisiuni": "permissions",
    "angajat": "employé",
    "angajați": "employés",
    "Vede panoul principal": "Voit le tableau de bord",
    "Vede șantierele — cifrat, marjă, cine a lucrat": "Voit les chantiers — chiffre d'affaires, marge, qui a travaillé",
    "Poate adăuga șantiere, pontaje și materiale pe ele": "Peut ajouter des chantiers, des heures et des matériaux",
    "Vede și modifică planingul": "Voit et modifie le planning",
    "Materiale — adaugă, scade, prețuri": "Matériaux — ajoute, retire, prix",
    "Scule — adaugă, alocă pe echipe": "Outils — ajoute, alloue aux équipes",
    "Camioane și utilaje — ITP, întreținere, combustibil": "Camions et engins — contrôle technique, entretien, carburant",
    "Vede și aprobă cererile de pe teren": "Voit et approuve les demandes du terrain",
    "Rapoarte": "Rapports",
    "Cifre și rentabilitate — marje, aport pe om": "Chiffres et rentabilité — marges, apport par personne",
    "Raport lunar pe fiecare angajat": "Rapport mensuel par employé",
    "Echipe": "Équipes",
    "Verifică dotarea standard a echipelor": "Vérifie l'équipement standard des équipes",
    "Oameni": "Personnes",
    "Vede angajații și fișele lor": "Voit les employés et leurs fiches",
    "Poate adăuga, modifica sau șterge angajați": "Peut ajouter, modifier ou supprimer des employés",
    "Pe teren (contul de muncitor)": "Sur le terrain (compte ouvrier)",
    "Notează de pe telefon ce materiale s-au consumat": "Note depuis le téléphone les matériaux consommés",
    "Poate cere oameni în plus pe șantierul lui": "Peut demander du personnel supplémentaire sur son chantier",
    "Vezi fișele, dar doar proprietarul poate adăuga, modifica sau șterge angajați.": "Tu vois les fiches, mais seul le propriétaire peut ajouter, modifier ou supprimer des employés.",
    "Vezi fișele, dar nu le poți modifica — rolul tău nu are voie.": "Tu vois les fiches, mais tu ne peux pas les modifier — ton rôle ne le permet pas.",
    "Doar proprietarul poate modifica sau șterge angajați.": "Seul le propriétaire peut modifier ou supprimer des employés.",
    "Funcție / rol": "Fonction / rôle",
    "— fără —": "— aucun —",
    "N-ai creat încă niciun rol. Le faci din Setări → Roluri și permisiuni.": "Tu n'as pas encore créé de rôle. Fais-le depuis Réglages → Rôles et permissions.",
    "Niciun rol definit — creează-le din Setări → Roluri și permisiuni.": "Aucun rôle défini — crée-les depuis Réglages → Rôles et permissions.",
    "Concediu de odihnă": "Congé payé",
    "Zi liberă": "Jour de congé",
    "Concediu medical": "Arrêt maladie",
    "Fără plată": "Sans solde",
    "Eveniment familial": "Événement familial",
    "Absență nemotivată": "Absence injustifiée",
    "🏖 Cer concediu": "🏖 Demander un congé",
    "📅 Cer o zi liberă": "📅 Demander un jour de congé",
    "Concediile tale": "Tes congés",
    "zi lucrătoare": "jour ouvré",
    "zile lucrătoare": "jours ouvrés",
    "Aprobat": "Approuvé",
    "Refuzat": "Refusé",
    "În așteptare": "En attente",
    "N-a venit la muncă": "N'est pas venu travailler",
    "Trece un concediu": "Enregistrer un congé",
    "Cerere de zi liberă": "Demande de jour de congé",
    "Cerere de concediu": "Demande de congé",
    "O singură zi": "Un seul jour",
    "Mai multe zile": "Plusieurs jours",
    "În ce zi": "Quel jour",
    "De la": "Du",
    "Până la (inclusiv)": "Au (inclus)",
    "Data de final trebuie să fie după cea de start.": "La date de fin doit être après celle de début.",
    "Ce fel de concediu": "Quel type de congé",
    "Pentru cine": "Pour qui",
    "Observații": "Observations",
    "De ce (opțional)": "Pourquoi (facultatif)",
    "Cererea ajunge la șef, care o aprobă sau o refuză.": "La demande arrive au chef, qui l'approuve ou la refuse.",
    "Marchează absența": "Marquer l'absence",
    "Trece concediul": "Enregistrer le congé",
    "Cer ziua asta liberă": "Demander ce jour de congé",
    "Trimite cererea": "Envoyer la demande",
    "🏖 Concedii": "🏖 Congés",
    "de aprobat": "à approuver",
    "+ Trec eu un concediu": "+ J'enregistre un congé",
    "🚫 N-a venit cineva": "🚫 Quelqu'un n'est pas venu",
    "🚫 N-a venit cineva astăzi": "🚫 Quelqu'un n'est pas venu aujourd'hui",
    "Nimic de aprobat.": "Rien à approuver.",
    "Concedii aprobate și refuzate": "Congés approuvés et refusés",
    "Aprobă": "Approuver",
    "Refuză": "Refuser",
    "Anulează concediul": "Annuler le congé",
    "🏖 În concediu": "🏖 En congé",
    "🚫 N-au venit": "🚫 Ne sont pas venus",
    "E indisponibil": "Est indisponible",
    "Sunt indisponibili": "Sont indisponibles",
    "Ce fel de vehicul": "Quel type de véhicule",
    "🚛 Camion": "🚛 Camion",
    "🏗 Utilaj greu": "🏗 Engin lourd",
    "🔧 Sculă comună": "🔧 Outil partagé",
    "Excavator, telescopic, dumper — utilaj greu, urmărit pe șantier.": "Pelleteuse, télescopique, dumper — engin lourd, suivi par chantier.",
    "Vibrator, generator, bac de beton, betonieră mică — sculă care circulă între echipe.": "Vibreur, groupe électrogène, bac à béton, petite bétonnière — outil qui circule entre équipes.",
    "Camion sau furgon cu placă de înmatriculare, alocat sau nu unei echipe.": "Camion ou fourgon immatriculé, assigné ou non à une équipe.",
    "Denumire *": "Nom *",
    "Număr / serie (opțional)": "Numéro / série (facultatif)",
    "Număr înmatriculare": "Numéro d'immatriculation",
    "Ore de funcționare": "Heures de fonctionnement",
    "Kilometraj": "Kilométrage",
    "Asigurare până la": "Assurance jusqu'au",
    "Următoarea revizie": "Prochaine révision",
    "Betonieră, excavator, telescopic, dumper, schelă — se urmăresc pe locație, nu pe echipă.": "Bétonnière, pelleteuse, télescopique, dumper, échafaudage — suivis par emplacement, pas par équipe.",
    "Utilaje comune": "Engins partagés",
    "Utilaje grele": "Engins lourds",
    "Scule comune": "Outils partagés",
    "Se urmăresc pe locație.": "Suivis par emplacement.",
    "Cer utilajul ăsta": "Je demande cet engin",
    "✓ Cerut — așteaptă răspunsul șefului": "✓ Demandé — en attente de réponse du chef",
    "Camioane și utilaje": "Camions et engins",
    "Mută": "Déplacer",
    "Adu la depozit": "Ramener au dépôt",
    "Înapoi în depozit": "Retour au dépôt",
    "Service": "Atelier",
    "A revenit reparată": "De retour, réparé",
    "Cât te-a costat reparația (€)": "Combien t'a coûté la réparation (€)",
    "Ce s-a reparat (opțional)": "Qu'est-ce qui a été réparé (facultatif)",
    "Marchează reparată": "Marquer réparé",
    "Împrumută un șofer": "Emprunter un chauffeur",
    "Echipe fără șofer": "Équipes sans chauffeur",
    "Îl împrumut": "Je l'emprunte",
    "Îl pun oricum": "Je le mets quand même",
    "Disponibili doar parțial": "Disponibles partiellement",
    "Golește ziua": "Vider la journée",
    "Golește": "Vider",
    "Categorii": "Catégories",
    "materiale și scule — adaugă, redenumește, șterge": "matériaux et outils — ajoute, renomme, supprime",
    "Firmă, program, acces": "Entreprise, horaires, accès",
    "Normă întreagă": "Temps plein",
    "Ore pe săptămână": "Heures par semaine",
    "Taxe pe salarii": "Charges sur salaires",
    "Închiderea firmei": "Fermeture de l'entreprise",
    "Adaugă perioadă": "Ajouter une période",
    "Firma e închisă": "L'entreprise est fermée",
    "Cifre și rentabilitate": "Chiffres et rentabilité",
    "marje, aport pe om, pierderi": "marges, apport par personne, pertes",
    "Oameni și echipe": "Personnes et équipes",
    "angajați, fișe, echipe": "employés, fiches, équipes",
    "Raport lunar": "Rapport mensuel",
    "ore și costuri pe fiecare om": "heures et coûts par personne",
    "Dotare echipe": "Équipement des équipes",
    "sculele obligatorii, verificări": "outils obligatoires, vérifications",
    "ITP, asigurări, revizii, locație": "contrôle technique, assurances, révisions, emplacement",
    "date firmă, orar, PIN, limbă": "données entreprise, horaires, code, langue",
    "Invită muncitorii": "Inviter les ouvriers",
    "linkuri și parole": "liens et mots de passe",
    "Backup și curățenie": "Sauvegarde et nettoyage",
    "salvare, restaurare, poze": "sauvegarde, restauration, photos",
    "🔧 Ale echipei": "🔧 De l'équipe",
    "🏗 Utilaje comune": "🏗 Engins partagés",
    "🏗 Utilaje": "🏗 Engins",
    "🔧 Scule": "🔧 Outils",
    "🚛 Camioane": "🚛 Camions",
    "Niciun camion încă.": "Aucun camion pour l'instant.",
    "Niciun utilaj încă.": "Aucun engin pour l'instant.",
    "Nicio sculă comună încă.": "Aucun outil partagé pour l'instant.",
    "Excavator, telescopic, dumper — se urmăresc pe locație, nu pe echipă.": "Pelleteuse, télescopique, dumper — suivis par emplacement, pas par équipe.",
    "Vibrator, generator, bac de beton, betonieră mică — circulă între echipe după nevoie.": "Vibreur, groupe électrogène, bac à béton, petite bétonnière — circulent entre équipes selon le besoin.",
    "Ștergi această cerere de concediu?": "Supprimer cette demande de congé ?",
    "Ștergi acest vehicul?": "Supprimer ce véhicule ?",
    "Ștergi acest utilaj?": "Supprimer cet engin ?",
    "Ștergi acest rol?": "Supprimer ce rôle ?",
    "Cifrat pe lucrări": "Chiffre d'affaires",
    "Marjă netă (cu pierderi)": "Marge nette (avec pertes)",
    "⚠ Pierdere (cu materialele pierdute)": "⚠ Perte (avec matériaux perdus)",
    "Stoc scăzut": "Stock faible",
    "Cereri noi de pe teren": "Nouvelles demandes du terrain",
    "✉ Cereri noi de pe teren": "✉ Nouvelles demandes du terrain",
    "Șantiere active": "Chantiers actifs",
    "Manoperă pontată (total)": "Main-d'œuvre pointée (total)",
    "🚛 De rezolvat la mașini": "🚛 À régler sur les véhicules",
    "🔧 Scule raportate cu probleme": "🔧 Outils signalés en panne",
    "⚠ Necesită aprovizionare": "⚠ Besoin de réapprovisionnement",
    "Verifică acte": "Vérifier les papiers",
    "În regulă": "En règle",
    "Bilanț": "Bilan",
    "Bilanț general": "Bilan général",
    "Manoperă pontată": "Main-d'œuvre pointée",
    "Materiale pe șantiere": "Matériaux sur chantiers",
    "Materiale fără destinație": "Matériaux sans destination",
    "Marjă netă": "Marge nette",
    "Marjă": "Marge",
    "Manoperă": "Main-d'œuvre",
    "Auto (combustibil/întreținere)": "Véhicules (carburant/entretien)",
    "🏢 Personal de birou (estimat lunar)": "🏢 Personnel de bureau (estimation mensuelle)",
    "Materiale consumate fără șantier": "Matériaux consommés sans chantier",
    "Nimic nealocat — tot ce a ieșit din depozit are un șantier în spate.": "Rien de non attribué — tout ce qui est sorti du dépôt a un chantier associé.",
    "Vezi toate ieșirile": "Voir toutes les sorties",
    "Marjă pe șantier": "Marge par chantier",
    "Niciun șantier de analizat.": "Aucun chantier à analyser.",
    "Niciun pontaj înregistrat încă.": "Aucune heure enregistrée pour l'instant.",
    "Ce tip de lucrare îți iese mai bine": "Quel type de travaux est le plus rentable",
    "Adaugă șantiere cu tip de lucrare ca să vezi comparația.": "Ajoute des chantiers avec un type de travaux pour voir la comparaison.",
    "Cost real (manoperă + materiale)": "Coût réel (main-d'œuvre + matériaux)",
    "Șantier": "Chantier",
    "Pe faze": "Par phases",
    "Pe ce fază": "Pour quelle phase",
    "— nealocat pe fază —": "— non attribué à une phase —",
    "Echipă": "Équipe",
    "+ Întreținere": "+ Entretien",
    "Adaugă o categorie nouă": "Ajouter une nouvelle catégorie",
    "Redenumește": "Renommer",
    "🏠 În depozit": "🏠 Au dépôt",
    "Km curent (opțional)": "Km actuel (facultatif)",
    "Pe ce șantier (opțional)": "Sur quel chantier (facultatif)",
    "Note (opțional)": "Notes (facultatif)",
    "Preț / unitate (€)": "Prix / unité (€)",
    "— fără categorie —": "— sans catégorie —",
    "+ Categorie nouă…": "+ Nouvelle catégorie…",
    "Unde lucrează": "Où il travaille",
    "🏢 La birou": "🏢 Au bureau",
    "Pe ce șantier": "Sur quel chantier",
    "Tip de lucrare": "Type de travaux",
    "Ore prevăzute": "Heures prévues",
    "+ Adaugă linie": "+ Ajouter une ligne",
    "+ Adaugă material": "+ Ajouter un matériau",
    "Inventar gol. Adaugă materialele cu preț ca să vezi valoarea stocului.": "Inventaire vide. Ajoute les matériaux avec un prix pour voir la valeur du stock.",
    "+ Adaugă sculă": "+ Ajouter un outil",
    "La service": "En réparation",
    "Revenită în depozit": "Revenu au dépôt",
    "Alocă": "Attribuer",
    "Returnează": "Retourner",
    "Nicio sculă. Adaugă-le cu preț ca să știi valoarea parcului de scule.": "Aucun outil. Ajoute-les avec un prix pour connaître la valeur du parc d'outils.",
    "Angajați": "Employés",
    "+ Adaugă angajat": "+ Ajouter un employé",
    "Fișă →": "Fiche →",
    "+ Adaugă echipă": "+ Ajouter une équipe",
    "Gestionează membri": "Gérer les membres",
    "Nicio echipă încă.": "Aucune équipe pour l'instant.",
    "+ Adaugă șantier": "+ Ajouter un chantier",
    "nimeni n-a lucrat încă aici": "personne n'a encore travaillé ici",
    "Copiază în săptămâna următoare": "Copier vers la semaine suivante",
    "🚗 Echipe fără șofer": "🚗 Équipes sans chauffeur",
    "Adaugă întâi un șantier ca să poți planifica pe el.": "Ajoute d'abord un chantier pour pouvoir y planifier.",
    "O poți schimba oricând din Setări.": "Tu peux la changer à tout moment depuis Réglages.",
    "Azi n-ai nimic în planing. Întreabă șeful dacă nu ești sigur.": "Tu n'as rien au planning aujourd'hui. Demande au chef si tu n'es pas sûr.",
    "Mâine": "Demain",
    "Mâine nu e nimic pus încă. Verifică diseară — șeful mai schimbă.": "Rien de prévu pour demain encore. Vérifie ce soir — le chef peut changer.",
    "Nicio sculă comună marcată.": "Aucun outil partagé marqué.",
    "Alimentările tale": "Tes ravitaillements",
    "Echipa ta n-are nicio sculă alocată acum.": "Ton équipe n'a aucun outil attribué en ce moment.",
    "Notate de tine": "Notés par toi",
    "Încă nimic. Apasă butonul galben după ce ați folosit ceva.": "Rien pour l'instant. Appuie sur le bouton jaune après avoir utilisé quelque chose.",
    "ultimele 30 de zile": "les 30 derniers jours",
    "Nu ai încă ore pontate. Șeful le trece după fiecare zi de lucru.": "Tu n'as pas encore d'heures pointées. Le chef les enregistre après chaque journée.",
    "Pe șantier": "Sur le chantier",
    "Ce ai lucrat": "Ce que tu as fait",
    "Săptămâna asta": "Cette semaine",
    "Ieși din cont": "Se déconnecter",
    "Ieșire din cont": "Déconnexion",
    "Te întorci la ecranul de intrare. Datele rămân salvate.": "Tu reviens à l'écran de connexion. Les données restent enregistrées.",
    "Ieși din contul de admin": "Se déconnecter du compte admin",
    "Date în aplicație": "Données dans l'application",
    "+ Adaugă": "+ Ajouter",
    "🗑 Cheltuieli fără vehicul": "🗑 Dépenses sans véhicule",
    "Salvează pe telefon": "Enregistrer sur le téléphone",
    "Backup complet (cu poze)": "Sauvegarde complète (avec photos)",
    "Doar datele (fișier mic)": "Données seulement (fichier léger)",
    "🧹 Curățenie automată a pozelor": "🧹 Nettoyage automatique des photos",
    "🧹 Curățenie cereri și ore suplimentare": "🧹 Nettoyage des demandes et heures sup",
    "Copie rapidă în aplicație": "Copie rapide dans l'application",
    "Fă o copie acum": "Faire une copie maintenant",
    "Reîmprospătează lista": "Actualiser la liste",
    "Restaurează": "Restaurer",
    "Restaurare din fișier": "Restauration depuis un fichier",
    "· costă": "· coûte",
    "trecut de tine": "enregistré par toi",
    "Istoric alimentări": "Historique des ravitaillements",
    "· nu e în stoc": "· pas en stock",
    "Marchează rezolvată": "Marquer résolue",
    "Nicio intervenție notată.": "Aucune intervention notée.",
    "🗂️ Categoriile tale de scule": "🗂️ Tes catégories d'outils",
    "Adaugă în listă": "Ajouter à la liste",
    "Verificare pe echipe": "Vérification par équipe",
    "Nicio echipă de verificat.": "Aucune équipe à vérifier.",
    "Scrie întâi lista de mai sus.": "Écris d'abord la liste ci-dessus.",
    "Neverificată": "Non vérifiée",
    "nu apare nimic alocat echipei": "rien n'est attribué à l'équipe",
    "Nicio verificare încă.": "Aucune vérification encore.",
    "Ce s-a întâmplat cu ea?": "Qu'est-ce qui s'est passé ?",
    "Spune pe scurt ce s-a întâmplat": "Explique brièvement ce qui s'est passé",
    "Șeful primește imediat mesajul.": "Le chef reçoit le message immédiatement.",
    "Nu ești pe niciun șantier activ. Vorbește cu șeful.": "Tu n'es sur aucun chantier actif. Parle au chef.",
    "👁 Ce văd muncitorii": "👁 Ce que voient les ouvriers",
    "💰 Taxe pe salarii": "💰 Charges sur salaires",
    "🕖 Programul de lucru": "🕖 Horaires de travail",
    "🏖 Închiderea firmei": "🏖 Fermeture de l'entreprise",
    "📅 Normă întreagă": "📅 Temps plein",
    "h/săptămână": "h/semaine",
    "Limba aplicației": "Langue de l'application",
    "Schimbă PIN": "Changer le code PIN",
    "Forma juridică": "Forme juridique",
    "Monedă": "Devise",
    "Oraș": "Ville",
    "Adresă": "Adresse",
    "Cât ai cumpărat *": "Combien tu as acheté *",
    "Poză bon (opțional)": "Photo du ticket (facultatif)",
    "Câte ore aprobi": "Combien d'heures tu approuves",
    "De ce ai schimbat (îl vede omul)": "Pourquoi tu as changé (visible par la personne)",
    "Prag minim (alertă)": "Seuil minimum (alerte)",
    "Locație": "Emplacement",
    "Marfa nu intră în stoc — se trece direct pe": "La marchandise n'entre pas en stock — elle va directement sur",
    "Intră în stoc, la depozit. De acolo îl repartizezi pe șantiere când pleacă.": "Ça entre en stock, au dépôt. De là tu le répartis sur les chantiers quand il part.",
    "Ai mai cheltuit cu ea până acum:": "Tu as déjà dépensé avec lui jusqu'ici :",
    "Preț achiziție (€)": "Prix d'achat (€)",
    "Nume echipă *": "Nom de l'équipe *",
    "Niciun vehicul în evidență — le adaugi din Setări → Camioane.": "Aucun véhicule enregistré — ajoute-les depuis Réglages → Camions.",
    "Șantier fix (opțional)": "Chantier fixe (facultatif)",
    "— fără, se stabilește prin planing —": "— aucun, défini via le planning —",
    "🏗 Pe șantier": "🏗 Sur chantier",
    "Data angajării": "Date d'embauche",
    "Cost orar (€/h) *pentru calcul": "Coût horaire (€/h) *pour le calcul",
    "Detalii plată": "Détails du paiement",
    "Notează de pe telefonul lui ce s-a consumat pe șantier": "Note depuis son téléphone ce qui a été consommé sur le chantier",
    "Poate duce camionul echipei — fiecare echipă are nevoie de cel puțin unul": "Peut conduire le camion de l'équipe — chaque équipe a besoin d'au moins un chauffeur",
    "Rol de firmă": "Rôle dans l'entreprise",
    "Angajat din": "Employé depuis",
    "Plată": "Paiement",
    "Poate scădea din stoc": "Peut retirer du stock",
    "Permis de conducere": "Permis de conduire",
    "Cont aplicație": "Compte application",
    "Ce a lucrat": "Ce qu'il a fait",
    "Mută rapid în altă echipă": "Déplacer rapidement vers une autre équipe",
    "Modifică fișa": "Modifier la fiche",
    "Șterge angajatul": "Supprimer l'employé",
    "Ce s-a făcut *": "Ce qui a été fait *",
    "Km la intervenție": "Km à l'intervention",
    "— fără, cost general —": "— aucun, coût général —",
    "Nu e nimic în depozit. Scrie mai sus ce vă trebuie.": "Il n'y a rien au dépôt. Écris ci-dessus ce qu'il te faut.",
    "— altundeva / nu e legat de un șantier —": "— ailleurs / pas lié à un chantier —",
    "Ce vă trebuie": "Ce qu'il te faut",
    "în depozit:": "au dépôt :",
    "Altceva de spus (opțional)": "Autre chose à dire (facultatif)",
    "Pentru ce zi": "Pour quel jour",
    "Câți oameni în plus îți trebuie": "Combien de personnes en plus il te faut",
    "De când": "Depuis quand",
    "De ce ai nevoie de ei": "Pourquoi tu en as besoin",
    "Ce ai nevoie legat de planing": "Ce dont tu as besoin pour le planning",
    "De la ora": "À partir de",
    "Până la ora": "Jusqu'à",
    "Pauza de masă (nu se plătește)": "Pause déjeuner (non payée)",
    "Zile lucrătoare": "Jours ouvrés",
    "schimbă": "changer",
    "verifică": "vérifier",
    "Nu găsesc materialul. Cere-i șefului să-l adauge în stoc.": "Je ne trouve pas le matériau. Demande au chef de l'ajouter au stock.",
    "Poți nota oricum — stocul ajunge la 0 și șeful vede că nu se potrivește.": "Tu peux noter quand même — le stock passe à 0 et le chef voit que ça ne correspond pas.",
    "Cum ajung oamenii în aplicație": "Comment les gens accèdent à l'application",
    "Linkul aplicației": "Lien de l'application",
    "Mesaj pentru fiecare om": "Message pour chaque personne",
    "Niciun angajat. Adaugă-i întâi la Oameni și echipe.": "Aucun employé. Ajoute-les d'abord dans Personnes et équipes.",
    "De reținut": "À retenir",
    "🖨 Salvează ca PDF / Tipărește": "🖨 Enregistrer en PDF / Imprimer",
    "✕ Închide": "✕ Fermer",
    "Fază": "Phase",
    "Pe fiecare om, câte ore pe șantier": "Par personne, combien d'heures par chantier",
    "Zile cu program diferit": "Jours avec horaires différents",
    "Până la": "Jusqu'à",
    "Pauză": "Pause",
    "De ce? (îl vede omul)": "Pourquoi ? (visible par la personne)",
    "în plus": "en plus",
    "Câte ore în plus": "Combien d'heures en plus",
    "De ce ai stat peste program": "Pourquoi tu es resté après l'heure",
    "📄 Raport lunar pe fiecare om": "📄 Rapport mensuel par personne",
    "Fază fără nume": "Phase sans nom",
    "Cifrat pe fază": "Chiffre d'affaires par phase",
    "Data începerii": "Date de début",
    "Adresa completă (pentru navigare)": "Adresse complète (pour la navigation)",
    "Oamenii apasă un buton și li se deschide în hărți.": "Les gens appuient sur un bouton et ça s'ouvre dans les cartes.",
    "Devizul — ce ai prevăzut": "Le devis — ce que tu as prévu",
    "O sumă": "Un montant",
    "La cât ai cifrat lucrarea (€)": "À combien tu as chiffré les travaux (€)",
    "Din inventar": "Depuis l'inventaire",
    "— altul, îl scriu eu —": "— autre, je l'écris —",
    "Salvează consumul": "Enregistrer la consommation",
    "Pe ce fază au lucrat *": "Sur quelle phase ils ont travaillé *",
    "(pentru toți, dacă nu schimbi mai jos)": "(pour tous, sauf changement ci-dessous)",
    "Au făcut lucruri diferite": "Ils ont fait des choses différentes",
    "Alegi separat pentru fiecare om": "Tu choisis séparément pour chaque personne",
    "⚠ Sunt deja pontați în ziua asta": "⚠ Déjà pointés ce jour-là",
    "📍 Adresă": "📍 Adresse",
    "plătită": "payée",
    "Prevăzut vs realizat": "Prévu vs réalisé",
    "Niciun material notat pe acest șantier.": "Aucun matériau noté sur ce chantier.",
    "Ore pe tip de muncă": "Heures par type de travail",
    "Niciun pontaj încă.": "Aucune heure encore.",
    "Intrări pontaj": "Entrées d'heures",
    "Niciun angajat în evidență.": "Aucun employé enregistré.",
    "· fără echipă": "· sans équipe",
    "Șantier *": "Chantier *",
    "De la ora *": "À partir de *",
    "Până la ora *": "Jusqu'à *",
    "Oameni în plus (din alte echipe)": "Personnes en plus (d'autres équipes)",
    "Ce se face / observații": "Ce qui se fait / observations",
    "ℹ Sunt deja puși aici": "ℹ Déjà mis ici",
    "🏖 Firma e închisă în ziua asta": "🏖 L'entreprise est fermée ce jour-là",
    "Poți salva oricum, dacă e o excepție.": "Tu peux quand même enregistrer, si c'est une exception.",
    "⛔ Suprapunere de program": "⛔ Chevauchement d'horaire",
    "între": "entre",
    "Sau schimbi tu orele de mai sus, ori scoți oamenii din listă.": "Ou tu changes les horaires ci-dessus, ou tu retires des personnes de la liste.",
    "Parolă nouă (minim 4 caractere)": "Nouveau mot de passe (4 caractères min.)",
    "Poza a fost ștearsă automat (problemă rezolvată)": "Photo supprimée automatiquement (problème résolu)",
    "+ Adaugă problemă cu poză": "+ Ajouter un problème avec photo",
    "Ce e de făcut *": "Ce qu'il faut faire *",
    "Poză": "Photo",
    "Nu știu / pierdere / consum intern": "Je ne sais pas / perte / usage interne",
    "Motiv (opțional)": "Motif (facultatif)",
    "Salvează PIN": "Enregistrer le code PIN",
    "e deja": "est déjà",
    "sunt deja": "sont déjà",
    "La": "À",
    "În service": "En réparation",
    "În depozit": "Au dépôt",
    "Caută…": "Rechercher…",
    "Caută angajat…": "Rechercher un employé…",
    "ex. Instalații electrice": "ex. Installations électriques",
    "ex. Secretariat, Achiziții, Șef șantier": "ex. Secrétariat, Achats, Chef de chantier",
    "ce s-a întâmplat? (pierdut, stricat, la altă echipă…)": "que s'est-il passé ? (perdu, cassé, chez une autre équipe…)",
    "ex. eu, sau numele șefului de echipă": "ex. moi, ou le nom du chef d'équipe",
    "Caută materialul…": "Rechercher le matériau…",
    "Lipește aici linkul după ce publici aplicația": "Colle ici le lien après avoir publié l'application",
    "strada, număr, cod poștal": "rue, numéro, code postal",
    "ex. ai stat 3h dar înregistrate erau doar 2h lucrate": "ex. tu es resté 3h mais seulement 2h étaient enregistrées",
    "ex. Zidărie": "ex. Maçonnerie",
    "ex. Echipa 1 — Zidărie": "ex. Équipe 1 — Maçonnerie",
    "ex. Ionuț Popescu": "ex. Jean Dupont",
    "ex. Schimb ulei + filtre, plăcuțe frână": "ex. Vidange + filtres, plaquettes de frein",
    "ex. Garaj Renault Angers, garanție 1 an": "ex. Garage Renault Angers, garantie 1 an",
    "Caută sau scrie ce vă trebuie…": "Cherche ou écris ce qu'il te faut…",
    "ex. ne ajunge până joi, aduceți dacă se poate mâine": "ex. ça suffit jusqu'à jeudi, apportez demain si possible",
    "ex. turnare placă joi, ne trebuie mână de lucru în plus o zi": "ex. coulage de dalle jeudi, on a besoin de renfort un jour",
    "ex. Echipa 1 ar trebui mutată luni pe alt șantier, clientul a cerut o zi mai devreme": "ex. l'équipe 1 devrait être déplacée lundi sur un autre chantier, le client a demandé un jour plus tôt",
    "ex. S-a stricat flexul mare, nu mai pornește": "ex. La grande meuleuse est en panne, elle ne démarre plus",
    "ex. Vacanța de vară, Sărbătorile de iarnă": "ex. Vacances d'été, Fêtes de fin d'année",
    "ex. nu erau aprobate dinainte, vorbim mâine": "ex. ce n'était pas approuvé à l'avance, on en parle demain",
    "ex. am terminat turnarea plăcii, nu se putea lăsa": "ex. j'ai fini de couler la dalle, ça ne pouvait pas attendre",
    "ex. Demolare interioară": "ex. Démolition intérieure",
    "ex. Casă P+1 Beaucouzé": "ex. Maison R+1 Beaucouzé",
    "ex. Turnare placă, vine betoniera la 9": "ex. Coulage de dalle, la bétonnière arrive à 9h",
    "ex. Refăcut colțul de la baie": "ex. Refaire le coin de la salle de bain",
    "ex. Nu e la plumb, se vede de la ușă. De reparat înainte de gletuit.": "ex. Ce n'est pas d'aplomb, ça se voit depuis la porte. À réparer avant l'enduit.",
    "ex. spart la descărcare, lipsă la inventar, dat împrumut": "ex. cassé au déchargement, manquant à l'inventaire, prêté",
  },
  en: {
    "Alege limba": "Choose your language",
    "Poți schimba oricând, din colțul de sus.": "You can change it anytime, from the top corner.",
    "🔑 Intru ca Admin": "🔑 Sign in as Admin",
    "👷 Intru ca Muncitor": "👷 Sign in as Worker",
    "🧪 Vezi un exemplu (demo)": "🧪 See an example (demo)",
    "sau": "or",
    "PIN admin": "Admin PIN",
    "Intră": "Sign in",
    "← Înapoi": "← Back",
    "PIN greșit.": "Wrong PIN.",
    "Cine ești?": "Who are you?",
    "— alege numele tău —": "— pick your name —",
    "Parola ta": "Your password",
    "Alege-ți o parolă (minim 4 cifre)": "Choose a password (min. 4 digits)",
    "E prima ta intrare — parola pe care o scrii acum rămâne a ta.":
      "This is your first sign-in — the password you type now becomes yours.",
    "Parolă greșită. Dacă ai uitat-o, cere-i șefului să ți-o reseteze.":
      "Wrong password. If you forgot it, ask the boss to reset it.",
    "Parola trebuie să aibă minim 4 caractere.": "Password must be at least 4 characters.",
    "Adminul trebuie mai întâi să te adauge la Oameni → Angajați.":
      "The admin must first add you under People → Employees.",
    "Ce e modul demo": "What demo mode is",
    "MOD DEMO": "DEMO MODE",
    "Date de exemplu. Nimic nu se salvează și nu-ți atinge datele reale.":
      "Sample data. Nothing is saved and your real data isn't touched.",
    "🔑 Intră ca Admin": "🔑 Enter as Admin",
    "Ieși": "Exit",
    "DEMO · Ieși": "DEMO · Exit",
    "Admin · Ieși": "Admin · Exit",
    "Cont șters": "Deleted account",
    "Fără echipă": "No team",
    "Sculele echipei tale": "Your team's tools",
    "La voi": "With you",
    "Cod": "Ref.",
    "din": "since",
    "Planingul tău": "Your schedule",
    "Azi": "Today",
    "Șantier șters": "Deleted site",
    "Orele tale": "Your hours",
    "Total:": "Total:",
    "Probleme și necesar": "Issues and needs",
    "+ Raportează o problemă / cere ceva": "+ Report an issue / request something",
    "N-ai trimis nimic încă. Lipsește material, s-a stricat o sculă, ai nevoie de ceva pe șantier — scrie aici și vede doar șeful.":
      "You haven't sent anything yet. Missing material, a broken tool, something you need on site — write it here, only the boss sees it.",
    "⚠ Problemă": "⚠ Issue",
    "📦 Necesar": "📦 Need",
    "Trimisă": "Sent",
    "Rezolvată": "Resolved",
    "Raportează": "Report",
    "📦 Am nevoie de…": "📦 I need…",
    "Ce s-a întâmplat?": "What happened?",
    "Ce vă lipsește pe șantier?": "What's missing on site?",
    "Mesajul ajunge doar la admin.": "The message goes only to the admin.",
    "Trimite": "Send",
    "De rezolvat": "To fix",
    "De făcut": "To do",
    "Rezolvat": "Done",
    "Marchează rezolvat": "Mark as done",
    "Redeschide": "Reopen",
    "Rezolvat de": "Done by",
    "Poza nu mai e disponibilă": "Photo no longer available",
    "Se încarcă poza…": "Loading photo…",
    "Panou": "Home",
    "Șantiere": "Sites",
    "Planing": "Schedule",
    "Stoc": "Stock",
    "Cereri": "Requests",
    "Setări": "Settings",
    "Salvează": "Save",
    "Modifică": "Edit",
    "Șterge": "Delete",
    "Adaugă": "Add",
    "Anulează": "Cancel",
    "Se încarcă…": "Loading…",
    "Se salvează…": "Saving…",
    "om": "person",
    "oameni": "people",
    "zi": "day",
    "zile": "days",
    "ore": "hours",
    "Luni": "Monday", "Marți": "Tuesday", "Miercuri": "Wednesday", "Joi": "Thursday",
    "Vineri": "Friday", "Sâmbătă": "Saturday", "Duminică": "Sunday",
    /* --- added: roles, leave, equipment, planning, categories, taxes --- */
    "Roluri și permisiuni": "Roles and permissions",
    "cine ce poate face în aplicație": "who can do what in the app",
    "🔑 Rolurile firmei": "🔑 Company roles",
    "+ Rol nou": "+ New role",
    "Rol nou": "New role",
    "Modifică rol": "Edit role",
    "Numele rolului *": "Role name *",
    "Salvează rolul": "Save role",
    "permisiune": "permission",
    "permisiuni": "permissions",
    "angajat": "employee",
    "angajați": "employees",
    "Vede panoul principal": "Sees the dashboard",
    "Vede șantierele — cifrat, marjă, cine a lucrat": "Sees sites — revenue, margin, who worked",
    "Poate adăuga șantiere, pontaje și materiale pe ele": "Can add sites, hours and materials",
    "Vede și modifică planingul": "Sees and edits the planning",
    "Materiale — adaugă, scade, prețuri": "Materials — add, remove, prices",
    "Scule — adaugă, alocă pe echipe": "Tools — add, assign to teams",
    "Camioane și utilaje — ITP, întreținere, combustibil": "Trucks and equipment — inspection, maintenance, fuel",
    "Vede și aprobă cererile de pe teren": "Sees and approves field requests",
    "Rapoarte": "Reports",
    "Cifre și rentabilitate — marje, aport pe om": "Figures and profitability — margins, contribution per person",
    "Raport lunar pe fiecare angajat": "Monthly report per employee",
    "Echipe": "Teams",
    "Verifică dotarea standard a echipelor": "Checks teams' standard kit",
    "Oameni": "People",
    "Vede angajații și fișele lor": "Sees employees and their profiles",
    "Poate adăuga, modifica sau șterge angajați": "Can add, edit or delete employees",
    "Pe teren (contul de muncitor)": "In the field (worker account)",
    "Notează de pe telefon ce materiale s-au consumat": "Logs consumed materials from the phone",
    "Poate cere oameni în plus pe șantierul lui": "Can request extra workers on their site",
    "Vezi fișele, dar doar proprietarul poate adăuga, modifica sau șterge angajați.": "You see the profiles, but only the owner can add, edit, or delete employees.",
    "Vezi fișele, dar nu le poți modifica — rolul tău nu are voie.": "You see the profiles, but can't edit them — your role doesn't allow it.",
    "Doar proprietarul poate modifica sau șterge angajați.": "Only the owner can edit or delete employees.",
    "Funcție / rol": "Role / position",
    "— fără —": "— none —",
    "N-ai creat încă niciun rol. Le faci din Setări → Roluri și permisiuni.": "You haven't created any role yet. Do it from Settings → Roles and permissions.",
    "Niciun rol definit — creează-le din Setări → Roluri și permisiuni.": "No role defined — create them from Settings → Roles and permissions.",
    "Concediu de odihnă": "Paid leave",
    "Zi liberă": "Day off",
    "Concediu medical": "Sick leave",
    "Fără plată": "Unpaid",
    "Eveniment familial": "Family event",
    "Absență nemotivată": "Unexcused absence",
    "🏖 Cer concediu": "🏖 Request leave",
    "📅 Cer o zi liberă": "📅 Request a day off",
    "Concediile tale": "Your leave",
    "zi lucrătoare": "working day",
    "zile lucrătoare": "working days",
    "Aprobat": "Approved",
    "Refuzat": "Rejected",
    "În așteptare": "Pending",
    "N-a venit la muncă": "Didn't come to work",
    "Trece un concediu": "Log a leave",
    "Cerere de zi liberă": "Day-off request",
    "Cerere de concediu": "Leave request",
    "O singură zi": "Single day",
    "Mai multe zile": "Multiple days",
    "În ce zi": "Which day",
    "De la": "From",
    "Până la (inclusiv)": "To (inclusive)",
    "Data de final trebuie să fie după cea de start.": "The end date must be after the start date.",
    "Ce fel de concediu": "What kind of leave",
    "Pentru cine": "For whom",
    "Observații": "Notes",
    "De ce (opțional)": "Why (optional)",
    "Cererea ajunge la șef, care o aprobă sau o refuză.": "The request goes to your manager, who approves or rejects it.",
    "Marchează absența": "Mark absence",
    "Trece concediul": "Log the leave",
    "Cer ziua asta liberă": "Request this day off",
    "Trimite cererea": "Send request",
    "🏖 Concedii": "🏖 Leave",
    "de aprobat": "to approve",
    "+ Trec eu un concediu": "+ Log a leave myself",
    "🚫 N-a venit cineva": "🚫 Someone didn't show up",
    "🚫 N-a venit cineva astăzi": "🚫 Someone didn't show up today",
    "Nimic de aprobat.": "Nothing to approve.",
    "Concedii aprobate și refuzate": "Approved and rejected leave",
    "Aprobă": "Approve",
    "Refuză": "Reject",
    "Anulează concediul": "Cancel leave",
    "🏖 În concediu": "🏖 On leave",
    "🚫 N-au venit": "🚫 Didn't show up",
    "E indisponibil": "Is unavailable",
    "Sunt indisponibili": "Are unavailable",
    "Ce fel de vehicul": "What kind of vehicle",
    "🚛 Camion": "🚛 Truck",
    "🏗 Utilaj greu": "🏗 Heavy equipment",
    "🔧 Sculă comună": "🔧 Shared tool",
    "Excavator, telescopic, dumper — utilaj greu, urmărit pe șantier.": "Excavator, telehandler, dumper — heavy equipment, tracked by site.",
    "Vibrator, generator, bac de beton, betonieră mică — sculă care circulă între echipe.": "Vibrator, generator, concrete tub, small mixer — tool that moves between teams.",
    "Camion sau furgon cu placă de înmatriculare, alocat sau nu unei echipe.": "Truck or van with a plate, assigned or not to a team.",
    "Denumire *": "Name *",
    "Număr / serie (opțional)": "Number / serial (optional)",
    "Număr înmatriculare": "Registration number",
    "Ore de funcționare": "Operating hours",
    "Kilometraj": "Mileage",
    "Asigurare până la": "Insurance until",
    "Următoarea revizie": "Next service",
    "Betonieră, excavator, telescopic, dumper, schelă — se urmăresc pe locație, nu pe echipă.": "Mixer, excavator, telehandler, dumper, scaffolding — tracked by location, not by team.",
    "Utilaje comune": "Shared equipment",
    "Utilaje grele": "Heavy equipment",
    "Scule comune": "Shared tools",
    "Se urmăresc pe locație.": "Tracked by location.",
    "Cer utilajul ăsta": "Request this equipment",
    "✓ Cerut — așteaptă răspunsul șefului": "✓ Requested — awaiting manager's reply",
    "Camioane și utilaje": "Trucks and equipment",
    "Mută": "Move",
    "Adu la depozit": "Bring to depot",
    "Înapoi în depozit": "Back to depot",
    "Service": "Service",
    "A revenit reparată": "Back, repaired",
    "Cât te-a costat reparația (€)": "How much did the repair cost (€)",
    "Ce s-a reparat (opțional)": "What was repaired (optional)",
    "Marchează reparată": "Mark repaired",
    "Împrumută un șofer": "Borrow a driver",
    "Echipe fără șofer": "Teams without a driver",
    "Îl împrumut": "Borrow them",
    "Îl pun oricum": "Assign anyway",
    "Disponibili doar parțial": "Partially available",
    "Golește ziua": "Clear the day",
    "Golește": "Clear",
    "Categorii": "Categories",
    "materiale și scule — adaugă, redenumește, șterge": "materials and tools — add, rename, delete",
    "Firmă, program, acces": "Company, schedule, access",
    "Normă întreagă": "Full time",
    "Ore pe săptămână": "Hours per week",
    "Taxe pe salarii": "Payroll taxes",
    "Închiderea firmei": "Company closure",
    "Adaugă perioadă": "Add period",
    "Firma e închisă": "The company is closed",
    "Cifre și rentabilitate": "Figures and profitability",
    "marje, aport pe om, pierderi": "margins, contribution per person, losses",
    "Oameni și echipe": "People and teams",
    "angajați, fișe, echipe": "employees, profiles, teams",
    "Raport lunar": "Monthly report",
    "ore și costuri pe fiecare om": "hours and costs per person",
    "Dotare echipe": "Team kit",
    "sculele obligatorii, verificări": "required tools, checks",
    "ITP, asigurări, revizii, locație": "inspection, insurance, service, location",
    "date firmă, orar, PIN, limbă": "company info, hours, PIN, language",
    "Invită muncitorii": "Invite workers",
    "linkuri și parole": "links and passwords",
    "Backup și curățenie": "Backup and cleanup",
    "salvare, restaurare, poze": "save, restore, photos",
    "🔧 Ale echipei": "🔧 Team's tools",
    "🏗 Utilaje comune": "🏗 Shared equipment",
    "🏗 Utilaje": "🏗 Equipment",
    "🔧 Scule": "🔧 Tools",
    "🚛 Camioane": "🚛 Trucks",
    "Niciun camion încă.": "No trucks yet.",
    "Niciun utilaj încă.": "No equipment yet.",
    "Nicio sculă comună încă.": "No shared tools yet.",
    "Excavator, telescopic, dumper — se urmăresc pe locație, nu pe echipă.": "Excavator, telehandler, dumper — tracked by location, not by team.",
    "Vibrator, generator, bac de beton, betonieră mică — circulă între echipe după nevoie.": "Vibrator, generator, concrete tub, small mixer — move between teams as needed.",
    "Ștergi această cerere de concediu?": "Delete this leave request?",
    "Ștergi acest vehicul?": "Delete this vehicle?",
    "Ștergi acest utilaj?": "Delete this equipment?",
    "Ștergi acest rol?": "Delete this role?",
    "Cifrat pe lucrări": "Revenue",
    "Marjă netă (cu pierderi)": "Net margin (with losses)",
    "⚠ Pierdere (cu materialele pierdute)": "⚠ Loss (with lost materials)",
    "Stoc scăzut": "Low stock",
    "Cereri noi de pe teren": "New field requests",
    "✉ Cereri noi de pe teren": "✉ New field requests",
    "Șantiere active": "Active sites",
    "Manoperă pontată (total)": "Total logged labor",
    "🚛 De rezolvat la mașini": "🚛 To fix on vehicles",
    "🔧 Scule raportate cu probleme": "🔧 Tools reported broken",
    "⚠ Necesită aprovizionare": "⚠ Needs restocking",
    "Verifică acte": "Check documents",
    "În regulă": "In order",
    "Bilanț": "Balance",
    "Bilanț general": "Overall balance",
    "Manoperă pontată": "Logged labor",
    "Materiale pe șantiere": "Materials on sites",
    "Materiale fără destinație": "Materials without destination",
    "Marjă netă": "Net margin",
    "Marjă": "Margin",
    "Manoperă": "Labor",
    "Auto (combustibil/întreținere)": "Vehicles (fuel/maintenance)",
    "🏢 Personal de birou (estimat lunar)": "🏢 Office staff (monthly estimate)",
    "Materiale consumate fără șantier": "Materials consumed without a site",
    "Nimic nealocat — tot ce a ieșit din depozit are un șantier în spate.": "Nothing unassigned — everything that left the depot is tied to a site.",
    "Vezi toate ieșirile": "See all outflows",
    "Marjă pe șantier": "Margin per site",
    "Niciun șantier de analizat.": "No site to analyze.",
    "Niciun pontaj înregistrat încă.": "No hours logged yet.",
    "Ce tip de lucrare îți iese mai bine": "Which type of work pays off best",
    "Adaugă șantiere cu tip de lucrare ca să vezi comparația.": "Add sites with a work type to see the comparison.",
    "Cost real (manoperă + materiale)": "Real cost (labor + materials)",
    "Șantier": "Site",
    "Pe faze": "By phase",
    "Pe ce fază": "For which phase",
    "— nealocat pe fază —": "— not assigned to a phase —",
    "Echipă": "Team",
    "+ Întreținere": "+ Maintenance",
    "Adaugă o categorie nouă": "Add a new category",
    "Redenumește": "Rename",
    "🏠 În depozit": "🏠 At the depot",
    "Km curent (opțional)": "Current mileage (optional)",
    "Pe ce șantier (opțional)": "On which site (optional)",
    "Note (opțional)": "Notes (optional)",
    "Preț / unitate (€)": "Price / unit (€)",
    "— fără categorie —": "— no category —",
    "+ Categorie nouă…": "+ New category…",
    "Unde lucrează": "Where they work",
    "🏢 La birou": "🏢 At the office",
    "Pe ce șantier": "On which site",
    "Tip de lucrare": "Type of work",
    "Ore prevăzute": "Planned hours",
    "+ Adaugă linie": "+ Add a line",
    "+ Adaugă material": "+ Add material",
    "Inventar gol. Adaugă materialele cu preț ca să vezi valoarea stocului.": "Empty inventory. Add materials with a price to see stock value.",
    "+ Adaugă sculă": "+ Add tool",
    "La service": "In service",
    "Revenită în depozit": "Back at depot",
    "Alocă": "Assign",
    "Returnează": "Return",
    "Nicio sculă. Adaugă-le cu preț ca să știi valoarea parcului de scule.": "No tools. Add them with a price to know the tool fleet's value.",
    "Angajați": "Employees",
    "+ Adaugă angajat": "+ Add employee",
    "Fișă →": "Profile →",
    "+ Adaugă echipă": "+ Add team",
    "Gestionează membri": "Manage members",
    "Nicio echipă încă.": "No team yet.",
    "+ Adaugă șantier": "+ Add site",
    "nimeni n-a lucrat încă aici": "no one has worked here yet",
    "Copiază în săptămâna următoare": "Copy to next week",
    "🚗 Echipe fără șofer": "🚗 Teams without a driver",
    "Adaugă întâi un șantier ca să poți planifica pe el.": "Add a site first so you can schedule on it.",
    "O poți schimba oricând din Setări.": "You can change it anytime from Settings.",
    "Azi n-ai nimic în planing. Întreabă șeful dacă nu ești sigur.": "You have nothing on the schedule today. Ask your manager if unsure.",
    "Mâine": "Tomorrow",
    "Mâine nu e nimic pus încă. Verifică diseară — șeful mai schimbă.": "Nothing set for tomorrow yet. Check tonight — the manager may still change it.",
    "Nicio sculă comună marcată.": "No shared tool marked.",
    "Alimentările tale": "Your fuel-ups",
    "Echipa ta n-are nicio sculă alocată acum.": "Your team has no tools assigned right now.",
    "Notate de tine": "Logged by you",
    "Încă nimic. Apasă butonul galben după ce ați folosit ceva.": "Nothing yet. Tap the yellow button after you've used something.",
    "ultimele 30 de zile": "last 30 days",
    "Nu ai încă ore pontate. Șeful le trece după fiecare zi de lucru.": "You have no hours logged yet. Your manager logs them after each work day.",
    "Pe șantier": "On site",
    "Ce ai lucrat": "What you worked on",
    "Săptămâna asta": "This week",
    "Ieși din cont": "Log out",
    "Ieșire din cont": "Log out",
    "Te întorci la ecranul de intrare. Datele rămân salvate.": "You'll return to the login screen. Your data stays saved.",
    "Ieși din contul de admin": "Log out of the admin account",
    "Date în aplicație": "Data in the app",
    "+ Adaugă": "+ Add",
    "🗑 Cheltuieli fără vehicul": "🗑 Expenses without a vehicle",
    "Salvează pe telefon": "Save to phone",
    "Backup complet (cu poze)": "Full backup (with photos)",
    "Doar datele (fișier mic)": "Data only (small file)",
    "🧹 Curățenie automată a pozelor": "🧹 Automatic photo cleanup",
    "🧹 Curățenie cereri și ore suplimentare": "🧹 Cleanup of requests and overtime",
    "Copie rapidă în aplicație": "Quick copy in the app",
    "Fă o copie acum": "Make a copy now",
    "Reîmprospătează lista": "Refresh the list",
    "Restaurează": "Restore",
    "Restaurare din fișier": "Restore from file",
    "· costă": "· costs",
    "trecut de tine": "logged by you",
    "Istoric alimentări": "Fuel-up history",
    "· nu e în stoc": "· not in stock",
    "Marchează rezolvată": "Mark resolved",
    "Nicio intervenție notată.": "No intervention logged.",
    "🗂️ Categoriile tale de scule": "🗂️ Your tool categories",
    "Adaugă în listă": "Add to list",
    "Verificare pe echipe": "Check by team",
    "Nicio echipă de verificat.": "No team to check.",
    "Scrie întâi lista de mai sus.": "Write the list above first.",
    "Neverificată": "Not checked",
    "nu apare nimic alocat echipei": "nothing assigned to the team",
    "Nicio verificare încă.": "No check yet.",
    "Ce s-a întâmplat cu ea?": "What happened to it?",
    "Spune pe scurt ce s-a întâmplat": "Briefly explain what happened",
    "Șeful primește imediat mesajul.": "Your manager gets the message right away.",
    "Nu ești pe niciun șantier activ. Vorbește cu șeful.": "You're not on any active site. Talk to your manager.",
    "👁 Ce văd muncitorii": "👁 What workers see",
    "💰 Taxe pe salarii": "💰 Payroll taxes",
    "🕖 Programul de lucru": "🕖 Work schedule",
    "🏖 Închiderea firmei": "🏖 Company closure",
    "📅 Normă întreagă": "📅 Full time",
    "h/săptămână": "h/week",
    "Limba aplicației": "App language",
    "Schimbă PIN": "Change PIN",
    "Forma juridică": "Legal form",
    "Monedă": "Currency",
    "Oraș": "City",
    "Adresă": "Address",
    "Cât ai cumpărat *": "How much you bought *",
    "Poză bon (opțional)": "Receipt photo (optional)",
    "Câte ore aprobi": "How many hours you approve",
    "De ce ai schimbat (îl vede omul)": "Why you changed it (visible to the person)",
    "Prag minim (alertă)": "Minimum threshold (alert)",
    "Locație": "Location",
    "Marfa nu intră în stoc — se trece direct pe": "Goods don't enter stock — they go directly to",
    "Intră în stoc, la depozit. De acolo îl repartizezi pe șantiere când pleacă.": "It enters stock, at the depot. From there you assign it to sites when it leaves.",
    "Ai mai cheltuit cu ea până acum:": "You've already spent on it so far:",
    "Preț achiziție (€)": "Purchase price (€)",
    "Nume echipă *": "Team name *",
    "Niciun vehicul în evidență — le adaugi din Setări → Camioane.": "No vehicles on record — add them from Settings → Trucks.",
    "Șantier fix (opțional)": "Fixed site (optional)",
    "— fără, se stabilește prin planing —": "— none, set via planning —",
    "🏗 Pe șantier": "🏗 On site",
    "Data angajării": "Hire date",
    "Cost orar (€/h) *pentru calcul": "Hourly cost (€/h) *for calculation",
    "Detalii plată": "Payment details",
    "Notează de pe telefonul lui ce s-a consumat pe șantier": "Logs from their phone what was consumed on site",
    "Poate duce camionul echipei — fiecare echipă are nevoie de cel puțin unul": "Can drive the team's truck — every team needs at least one",
    "Rol de firmă": "Company role",
    "Angajat din": "Employee since",
    "Plată": "Payment",
    "Poate scădea din stoc": "Can deduct from stock",
    "Permis de conducere": "Driving license",
    "Cont aplicație": "App account",
    "Ce a lucrat": "What they worked on",
    "Mută rapid în altă echipă": "Quickly move to another team",
    "Modifică fișa": "Edit profile",
    "Șterge angajatul": "Delete employee",
    "Ce s-a făcut *": "What was done *",
    "Km la intervenție": "Mileage at service",
    "— fără, cost general —": "— none, general cost —",
    "Nu e nimic în depozit. Scrie mai sus ce vă trebuie.": "There's nothing at the depot. Write above what you need.",
    "— altundeva / nu e legat de un șantier —": "— elsewhere / not tied to a site —",
    "Ce vă trebuie": "What you need",
    "în depozit:": "at the depot:",
    "Altceva de spus (opțional)": "Anything else to say (optional)",
    "Pentru ce zi": "For which day",
    "Câți oameni în plus îți trebuie": "How many extra people you need",
    "De când": "Since when",
    "De ce ai nevoie de ei": "Why you need them",
    "Ce ai nevoie legat de planing": "What you need regarding planning",
    "De la ora": "From",
    "Până la ora": "Until",
    "Pauza de masă (nu se plătește)": "Lunch break (unpaid)",
    "Zile lucrătoare": "Working days",
    "schimbă": "change",
    "verifică": "check",
    "Nu găsesc materialul. Cere-i șefului să-l adauge în stoc.": "Can't find the material. Ask your manager to add it to stock.",
    "Poți nota oricum — stocul ajunge la 0 și șeful vede că nu se potrivește.": "You can log it anyway — stock hits 0 and your manager sees the mismatch.",
    "Cum ajung oamenii în aplicație": "How people get into the app",
    "Linkul aplicației": "App link",
    "Mesaj pentru fiecare om": "Message for each person",
    "Niciun angajat. Adaugă-i întâi la Oameni și echipe.": "No employees. Add them first in People and teams.",
    "De reținut": "Keep in mind",
    "🖨 Salvează ca PDF / Tipărește": "🖨 Save as PDF / Print",
    "✕ Închide": "✕ Close",
    "Fază": "Phase",
    "Pe fiecare om, câte ore pe șantier": "Per person, hours per site",
    "Zile cu program diferit": "Days with different hours",
    "Până la": "Until",
    "Pauză": "Break",
    "De ce? (îl vede omul)": "Why? (visible to the person)",
    "în plus": "extra",
    "Câte ore în plus": "How many extra hours",
    "De ce ai stat peste program": "Why you stayed past hours",
    "📄 Raport lunar pe fiecare om": "📄 Monthly report per person",
    "Fază fără nume": "Unnamed phase",
    "Cifrat pe fază": "Revenue per phase",
    "Data începerii": "Start date",
    "Adresa completă (pentru navigare)": "Full address (for navigation)",
    "Oamenii apasă un buton și li se deschide în hărți.": "People tap a button and it opens in maps.",
    "Devizul — ce ai prevăzut": "The estimate — what you planned",
    "O sumă": "An amount",
    "La cât ai cifrat lucrarea (€)": "What you quoted the job at (€)",
    "Din inventar": "From inventory",
    "— altul, îl scriu eu —": "— other, I'll type it —",
    "Salvează consumul": "Save consumption",
    "Pe ce fază au lucrat *": "Which phase they worked on *",
    "(pentru toți, dacă nu schimbi mai jos)": "(for everyone, unless changed below)",
    "Au făcut lucruri diferite": "They did different things",
    "Alegi separat pentru fiecare om": "Choose separately for each person",
    "⚠ Sunt deja pontați în ziua asta": "⚠ Already logged for this day",
    "📍 Adresă": "📍 Address",
    "plătită": "paid",
    "Prevăzut vs realizat": "Planned vs actual",
    "Niciun material notat pe acest șantier.": "No material logged on this site.",
    "Ore pe tip de muncă": "Hours by work type",
    "Niciun pontaj încă.": "No hours logged yet.",
    "Intrări pontaj": "Time entries",
    "Niciun angajat în evidență.": "No employees on record.",
    "· fără echipă": "· no team",
    "Șantier *": "Site *",
    "De la ora *": "From *",
    "Până la ora *": "Until *",
    "Oameni în plus (din alte echipe)": "Extra people (from other teams)",
    "Ce se face / observații": "What's being done / notes",
    "ℹ Sunt deja puși aici": "ℹ Already assigned here",
    "🏖 Firma e închisă în ziua asta": "🏖 The company is closed that day",
    "Poți salva oricum, dacă e o excepție.": "You can still save, if it's an exception.",
    "⛔ Suprapunere de program": "⛔ Schedule overlap",
    "între": "between",
    "Sau schimbi tu orele de mai sus, ori scoți oamenii din listă.": "Either change the times above, or remove people from the list.",
    "Parolă nouă (minim 4 caractere)": "New password (min. 4 characters)",
    "Poza a fost ștearsă automat (problemă rezolvată)": "Photo auto-deleted (problem resolved)",
    "+ Adaugă problemă cu poză": "+ Add problem with photo",
    "Ce e de făcut *": "What needs to be done *",
    "Poză": "Photo",
    "Nu știu / pierdere / consum intern": "Don't know / loss / internal use",
    "Motiv (opțional)": "Reason (optional)",
    "Salvează PIN": "Save PIN",
    "e deja": "is already",
    "sunt deja": "are already",
    "La": "At",
    "În service": "In service",
    "În depozit": "At the depot",
    "Caută…": "Search…",
    "Caută angajat…": "Search employee…",
    "ex. Instalații electrice": "e.g. Electrical installations",
    "ex. Secretariat, Achiziții, Șef șantier": "e.g. Secretariat, Purchasing, Site manager",
    "ce s-a întâmplat? (pierdut, stricat, la altă echipă…)": "what happened? (lost, broken, with another team…)",
    "ex. eu, sau numele șefului de echipă": "e.g. me, or the team leader's name",
    "Caută materialul…": "Search material…",
    "Lipește aici linkul după ce publici aplicația": "Paste the link here after publishing the app",
    "strada, număr, cod poștal": "street, number, postal code",
    "ex. ai stat 3h dar înregistrate erau doar 2h lucrate": "e.g. you stayed 3h but only 2h were logged",
    "ex. Zidărie": "e.g. Masonry",
    "ex. Echipa 1 — Zidărie": "e.g. Team 1 — Masonry",
    "ex. Ionuț Popescu": "e.g. John Smith",
    "ex. Schimb ulei + filtre, plăcuțe frână": "e.g. Oil change + filters, brake pads",
    "ex. Garaj Renault Angers, garanție 1 an": "e.g. Renault garage, 1-year warranty",
    "Caută sau scrie ce vă trebuie…": "Search or type what you need…",
    "ex. ne ajunge până joi, aduceți dacă se poate mâine": "e.g. enough until Thursday, bring more tomorrow if possible",
    "ex. turnare placă joi, ne trebuie mână de lucru în plus o zi": "e.g. slab pour on Thursday, we need extra hands for a day",
    "ex. Echipa 1 ar trebui mutată luni pe alt șantier, clientul a cerut o zi mai devreme": "e.g. Team 1 should move to another site Monday, the client asked for a day earlier",
    "ex. S-a stricat flexul mare, nu mai pornește": "e.g. The big grinder is broken, won't start",
    "ex. Vacanța de vară, Sărbătorile de iarnă": "e.g. Summer break, Winter holidays",
    "ex. nu erau aprobate dinainte, vorbim mâine": "e.g. wasn't approved in advance, we'll talk tomorrow",
    "ex. am terminat turnarea plăcii, nu se putea lăsa": "e.g. finished pouring the slab, couldn't leave it",
    "ex. Demolare interioară": "e.g. Interior demolition",
    "ex. Casă P+1 Beaucouzé": "e.g. House 1st floor Beaucouzé",
    "ex. Turnare placă, vine betoniera la 9": "e.g. Slab pour, concrete truck arrives at 9",
    "ex. Refăcut colțul de la baie": "e.g. Redo the bathroom corner",
    "ex. Nu e la plumb, se vede de la ușă. De reparat înainte de gletuit.": "e.g. Not plumb, visible from the door. Fix before skimming.",
    "ex. spart la descărcare, lipsă la inventar, dat împrumut": "e.g. broken during unloading, missing from inventory, lent out",
  },
};
